name: Ubuntu CI

on:
  pull_request:
  push:

jobs:
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@focal
        with:
          cmake-args: '-DBUILDSYSTEM_TESTING=True'
  jammy-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Jammy CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@jammy
        with:
          cmake-args: '-DBUILDSYSTEM_TESTING=True -DGZ_ENABLE_RELOCATABLE_INSTALL=True'
  noble-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Noble CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@jrivero/jammy_fixes_1
        with:
          cmake-args: '-DBUILDSYSTEM_TESTING=True -DGZ_ENABLE_RELOCATABLE_INSTALL=True'
