name: Ubuntu CI

on:
  pull_request:
  push:
    branches:
      - 'ign-cmake[0-9]'
      - 'gz-cmake[0-9]'
      - 'main'

jobs:
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@focal
        with:
          cmake-args: '-DBUILDSYSTEM_TESTING=True'
  jammy-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Jammy CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@jammy
        with:
          cmake-args: '-DBUILDSYSTEM_TESTING=True -DGZ_ENABLE_RELOCATABLE_INSTALL=True'
  version_consistency:
    runs-on: ubuntu-latest
    name: Version consistency between cmake and package.xml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify version consistency
        run: |
          grep 'project(gz-cmake[0-9]* VERSION' CMakeLists.txt | sed -e 's@.*VERSION @@' -e 's@) *@@' > /tmp/cmake_version
          cat /tmp/cmake_version
          grep '<version>' package.xml | sed -e 's@ *<version>@@' -e 's@</version>@@' > /tmp/package_xml_version
          cat /tmp/package_xml_version
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install catkin-pkg
        run: pip3 install catkin-pkg
      - name: Verify version consistency
